[package]
authors = ["Cameron Dart <cdart2@illinois.edu>"]
edition = "2018"
name = "garfield"
version = "0.1.0"
license = "MIT"
keywords = [ "matematics" ]
description = "Garfield provides cat-egory theory abstractions"